### PR TITLE
added category support for APNS

### PR DESCRIPTION
**Pull request by timbotnik**
I'd like this method to support some more of the features added in iOS8.  We are developing a Meteor integration with the Apple Watch, which has the need to use the "category" field of the APNS payload to support custom notification actions.

This pull request adds category support for iOS8 custom actions as described here:
https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/IPhoneOSClientImp.html#//apple_ref/doc/uid/TP40008194-CH103-SW36

### CODE REVIEW

**Comment by timbotnik** [comment]
This is a minimum solution for #70, further work may be needed for the other send APIs, such as expanding schema validation etc.

**Comment by raix** [comment]
I think the schema check in the config plugin might have to be updated too?

**Comment by timbotnik** [comment]
@raix - when sending the notification, it only deals with the NPM apn package, so this is not a worry for the push plugin.  If you wanted to actually parse the category and pass it back up to JS / Meteor, then we'd need to go further but I would suggest to treat that as a separate issue.

**Comment by raix** [comment]
got it, thanks

**Comment by raix** [comment]
please help test 2.6.12-rc1

**Pull request merged**
