### PR TITLE
Enable multiple notifications on Android

### PR DESCRIPTION
**Pull request by ppryde**
@raix Currently on Android, the Push package overwrites each additional message sent to mobile device due to the Cordova Push plugin setting the `tag` value of the GCM message to 0 by default. This pull allows the setting of an optional `notId` parameter to be passed to the notification object and will cause the client device to display multiple messages in the notifications bar. Each of these can be individually overwritten on client or server by reusing the same notId. 

The `notId` can also be set to a random value to ensure that all message have their own notification in the notification bar. The exception to this is when the messages are undelivered and stack up server side in which case if a collapseKey is defined, only the latest message from each collapse key will be used (up to a limit of 4 collapseKeys).

The `notId` can only be a 32 bit Integer due to the limitations placed on it by the Cordova Push plugin which will parse the value as such. Notification validation has been updated to check for a valid Integer value as part of this pull.

### CODE REVIEW

**Comment by ppryde** [comment]
Fixed conflict with waitUntil commit

**Comment by raix** [comment]
Thanks @ppryde

**Comment by ppryde** [comment]
np thanks for merging

**Comment by raix** [comment]
please help test 2.6.12-rc1

**Pull request merged**
